### ISSUE TITLE
error: failed to run custom build command for libudev-sys v0.1.4

### ISSUE THREAD

**Issue by hpsaturn** [dephy-io/dephy-esp32c3-rust-boilerplate#2]
Hi,

I was trying to run this in my Linux, but I have this error, when I tried to install `espflash`. The complete output increasing the debug verbose is this:

```bash
   Compiling ring v0.17.8
   Compiling toml_edit v0.19.15
error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installwk4yAX/release/build/libudev-sys-ea2932616266fe39/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBUDEV_STATIC
  cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/avp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libudev-sys-0.1.4/build.rs:38:41:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libudev\n\nThe system library `libudev` required by crate `libudev-sys` was not found.\nThe file `libudev.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `libudev.pc`.\n"
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/std/src/panicking.rs:665:5
     1: core::panicking::panic_fmt
               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/core/src/panicking.rs:76:14
     2: core::result::unwrap_failed
               at /rustc/dff3e7ccd4a18958c938136c4ccdc853fcc86194/library/core/src/result.rs:1699:5
     3: core::result::Result<T,E>::unwrap
               at /home/avp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
     4: build_script_build::main
               at ./build.rs:38:5
     5: core::ops::function::FnOnce::call_once
               at /home/avp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `espflash v3.2.0`, intermediate artifacts can be found at `/tmp/cargo-installwk4yAX`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Previously I installed the lib on Ubuntu 22.04 like this:

```bash
sudo apt-get install libuv1-dev
```

Maybe the problem is with my environment? I have the next libraries installed:

```bash
esp32c3-boilerplate$ dpkg -l | grep libuv
ii  libuv1:amd64                               1.43.0-1ubuntu0.1                       amd64        asynchronous event notification library - runtime library
ii  libuv1-dev:amd64                           1.43.0-1ubuntu0.1                       amd64        asynchronous event notification library - development files
ii  libuvc-dev                                 0.0.6-1.1                               amd64        cross-platform library for USB video devices - development files
ii  libuvc0                                    0.0.6-1.1                               amd64        cross-platform library for USB video devices
esp32c3-boilerplate$ 
```

**Comment by hpsaturn** [comment]
Mmm, sorry, I found that is missing a dev library on the system, ans also in your README. I fixed the issue installing this missing library:

```bash
libudev-dev
```
